apiVersion: v1
kind: Service
metadata:
  name: client
  namespace: venturplex-taskify
spec:
  type: LoadBalancer
  selector:
    app: client
  ports:
    - protocol: TCP
      targetPort: client
      port: 4200
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  namespace: venturplex-taskify
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
        version: v1
    spec:
      containers:
        - name: client
          image: tasks_client
          imagePullPolicy: Never
          ports:
            - name: client
              containerPort: 4200
